name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        working-directory: Frontend
       run: vercel deploy --prod --token="${{ secrets.VERCEL_TOKEN }}" --scope="parzival225" --yes